### ISSUE TITLE
kubetctl get cs is depreacted

### ISSUE THREAD

**Issue by filipdadgar** [SeryioGonzalez/Kubernetes-the-hard-way-on-Azure#1]
Hi buddy, long time no see! :)

Love the work and while quickly checked through the scripts I saw something very common in oldskool people's repos :)

Nowadays I believe the preferred way to get status of components is:
kubectl get --raw='/readyz?verbose'  instead of kubectl get componentstatuses

Best,
Filip

**Comment by SeryioGonzalez** [comment]
Reviewed
